### PR TITLE
feat: Add the mongo service in the docker-compose

### PR DESCRIPTION
**Pull request by taorepoara**
#10 

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [x] I made my own code-review before requesting one

## Description of the changes
Add MongoDB management for the new data system

### CODE REVIEW

**Review by Nesqwik — CHANGES_REQUESTED** [review]
Mongo is working but i still have the error when it try to stop the env.

The new command is : 
```
ApplicationRunner.Environment.DynamicSupervisor.stop_env(1)
```

**Comment by Nesqwik** [comment]
I have a crash when i start the images for the first time : 
```
thread 'main' panicked at 'docker-compose exec exited with code 1:
        cmd: "docker" "compose" "-f" ".lenra/docker-compose.yml" "exec" "devtool" "bin/dev_tools" "rpc" "ApplicationRunner.Environment.DynamicSupervisor.stop_env(1)"
        stdout: 
        stderr: ** (exit) exited in: GenServer.stop({:via, :swarm, {ApplicationRunner.Environment.Supervisor, 1}}, :normal, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.12.2) lib/gen_server.ex:972: GenServer.stop/3
    (stdlib 3.15.2) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/code.ex:656: Code.eval_string_with_error_handling/3
', src/docker_compose.rs:260:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Then when i start again to update the app, it no longer crash.

there is two solutions IMO : 
- First one, update the devtool. Make `ApplicationRunner.Environment.DynamicSupervisor.stop_env(1)` return a success even when there is no env with this ID started.
- Second one, update the lenra_cli to not run the command if the devtool is started for the first time.

@taorepoara any preferences ?

**Comment by taorepoara** [comment]
I can change the cli to do not fail when this command fails because it's not only the first time but when the env is not started (isn't it ?)

**Comment by Nesqwik** [comment]
> I can change the cli to do not fail when this command fails because it's not only the first time but when the env is not started (isn't it ?)

Yes but the env starts automatically when the devtool starts if i'm not mistaken.
Anyway i've updated the devtool to fix this already :)

**Review by Nesqwik — APPROVED** [review]

**Review by Nesqwik — DISMISSED** [review]
All i can say is that it's working as intended.

I cannot give any review about the code quality.

**Review by shiipou — APPROVED** [review]

**Pull request merged**
